import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Properties } from "csstype";
import { useState } from "react";
import MinaClient from "../api/MinaClient";
import AccountDetails from "../types/AccountDetails";
import WalletSelector from "../components/WalletSelector";
import WalletView from "../components/WalletView";

const Home = () => {
  const minaClient = new MinaClient();
  const [selectedWallet, setSelectedWallet] = useState<string>();
  const [wallets, setWallets] = useState<string[]>();
  const [accountDetails, setAccountDetails] = useState<AccountDetails>();
  const [buttonText, setButtonText] = useState("Connect your wallet");

  const onConnect = async () => {
    if (!window.mina) {
      alert("No provider was found, please add the Auro Wallet extension");
    } else {
      setButtonText("Onboarding in progress");
      let data = await window.mina.requestAccounts().catch((err: any) => err);
      console.log(JSON.stringify(data));
      if (data.message) {
        setButtonText(data.message);
      } else {
        let publicKeys = data;
        setWallets(publicKeys);
        setSelectedWallet(publicKeys[0]);
        getAccountDetails(publicKeys[0]);
      }
    }
  };

  const getAccountDetails = async (publicKey: string) => {
    const resp = await minaClient.getAccountDetails(publicKey);
    if (resp.status == 200) {
      setAccountDetails(resp.data);
      console.log(JSON.stringify(resp.data));
    } else {
      alert("Error retrieving account details for public key: " + publicKey);
    }
  };

  const selectWallet = (publicKey: string) => {
    setSelectedWallet(publicKey);
    getAccountDetails(publicKey);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Mina Guardian Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={containerStyle}>
          <h1 className={styles.title}>Welcome to Mina Guardian Wallet</h1>
          {accountDetails == undefined ||
          selectedWallet == undefined ||
          wallets == undefined ? (
            <button style={connectButtonStyle} onClick={onConnect}>
              {buttonText}
            </button>
          ) : (
            <div style={walletContainerStyle}>
              <WalletSelector
                selectedWallet={selectedWallet}
                onSelect={selectWallet}
                wallets={wallets}
              />
              <WalletView
                publicKey={selectedWallet}
                balance={accountDetails.account.balance.total}
              />
            </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

const walletContainerStyle: Properties = {};

const containerStyle: Properties = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
};

const connectButtonStyle: Properties = {
  padding: "10px",
  borderRadius: "30px",
  fontSize: "1.5rem",
  marginTop: "50px",
};

export default Home;
